using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using GammaWorldCharacter.Gear;
using GammaWorldCharacter.Samples;
using GammaWorldCharacter.Serialization;
using NUnit.Framework;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json.Schema;

namespace GammaWorldCharacter.Test.Unit.Serialization
{
    [TestFixture]
    public class TestSerialization
    {
        [Test]
        public void TestValidSchema()
        {
            JsonCharacterSerializer characterSerializer;
            StringBuilder stringBuilder;

            characterSerializer = new JsonCharacterSerializer();
            try
            {
                JsonSchema.Parse(characterSerializer.Schema);

                // Autogenerated schema may be useful
                // string result = new JsonSchemaGenerator().Generate(typeof(CharacterJsonData)).ToString();
            }
            catch (Exception ex)
            {
                stringBuilder = new StringBuilder();
                stringBuilder.Append(ex.Message);
                stringBuilder.AppendFormat("\n\n{0}\n", 
                    NumberLines(characterSerializer.Schema));

                Assert.Fail(stringBuilder.ToString());
            }            
        }

        [Test()]
        public void TestJsonSerialization()
        {
            JsonCharacterSerializer characterSerializer;
            StringBuilder stringBuilder;
            //IList<string> messages;
            //JObject jObject;
            //JsonSchema jsonSchema;
            //JsonSchema gammaWorldCharacterSchema;
            string json;

            // TODO: Pass this in as a test
            Character character;
            Character newCharacter;
            character = Level01Characters.Clip;

            characterSerializer = new JsonCharacterSerializer();

            json = string.Empty;
            try
            {
                json = characterSerializer.Serialize(character);

                newCharacter = characterSerializer.Deserialize(json);

                Assert.That(newCharacter, Is.EqualTo(character), "Characters differ");
                Assert.That(newCharacter.GetHeldItem<Item>(Hand.Main), Is.EqualTo(character.GetHeldItem<Item>(Hand.Main)), 
                    "Main hands differ");
                Assert.That(newCharacter.GetHeldItem<Item>(Hand.Off), Is.EqualTo(character.GetHeldItem<Item>(Hand.Off)),
                    "Main hands differ");
                Assert.That(
                    Array.ConvertAll((Slot[]) Enum.GetValues(typeof (Slot)), x => newCharacter.GetEquippedItem<Item>(x)),
                    Is.EquivalentTo(Array.ConvertAll((Slot[]) Enum.GetValues(typeof(Slot)), x => character.GetEquippedItem<Item>(x))),
                    "Equipped items differ");
                Assert.That(
                    newCharacter.Gear.OrderBy(x => x.Name),
                    Is.EquivalentTo(character.Gear.OrderBy(x => x.Name))),
                    "Carried items differ");
            }
            catch (Exception ex)
            {
                stringBuilder = new StringBuilder();
                stringBuilder.AppendFormat("{0} Level {1} {2} {3}:\n\n",
                    character.Name, character.Level,
                    character.PrimaryOrigin.Name, character.SecondaryOrigin.Name);
                stringBuilder.AppendFormat("{0}\n\n", NumberLines(json));
                stringBuilder.Append(ex.Message);

                Assert.Fail(stringBuilder.ToString());
            }

            /*
            jsonSchema = JsonSchema.Parse(characterSerializer.Schema);
            gammaWorldCharacterSchema = jsonSchema.Properties["gamma_world_character"];

            // Test the serialized character matches the schema.
            json = characterSerializer.Serialize(character);
            jObject = JObject.Parse(json);
            if (!jObject.IsValid(gammaWorldCharacterSchema, out messages))
            {
                stringBuilder = new StringBuilder();
                stringBuilder.AppendFormat("{0} Level {1} {2} {3}:\n\n",
                    character.Name, character.Level, 
                    character.PrimaryOrigin.Name, character.SecondaryOrigin.Name);
                stringBuilder.AppendFormat("{0}\n", NumberLines(json));
                if (messages.Any())
                {
                    stringBuilder.Append("\nErrors:\n");
                    foreach (string message in messages)
                    {
                        stringBuilder.Append(message);
                        stringBuilder.AppendLine();
                    }
                }

                Assert.Fail(stringBuilder.ToString());
            }
            */
        }

        /// <summary>
        /// Add a line number before each line.
        /// </summary>
        /// <param name="text"></param>
        /// <returns></returns>
        public static string NumberLines(string text)
        {
            int i = 1;
            return string.Join("\n", text.Split('\n').Select(x => i++.ToString("000") + ' ' + x));
        }
    }
}
