using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;
using GammaWorldCharacter;
using GammaWorldCharacter.Gear;
using GammaWorldCharacter.Origins;
using GammaWorldCharacter.Powers;
using GammaWorldCharacter.Traits;
using GammaWorldCharacter.Samples;
using GammaWorldCharacter.Test.Integration;
using GammaWorldCharacter.Levels;

namespace GammaWorldCharacter.Test.Integration
{
    /// <summary> 
    /// Autogenerated character test
    /// </summary>
    [TestFixture]
    public class TestLevel03Hermes : CharacterTest
    {
        private Character testCharacter;

        [TestCase(ScoreType.Strength, 11)]
        [TestCase(ScoreType.Constitution, 7)]
        [TestCase(ScoreType.Dexterity, 17)]
        [TestCase(ScoreType.Intelligence, 5)]
        [TestCase(ScoreType.Wisdom, 20)]
        [TestCase(ScoreType.Charisma, 13)]
        [TestCase(ScoreType.StrengthModifier, 0)]
        [TestCase(ScoreType.ConstitutionModifier, -2)]
        [TestCase(ScoreType.DexterityModifier, 3)]
        [TestCase(ScoreType.IntelligenceModifier, -3)]
        [TestCase(ScoreType.WisdomModifier, 5)]
        [TestCase(ScoreType.CharismaModifier, 1)]
        [TestCase(ScoreType.Initiative, 14)]
        [TestCase(ScoreType.HitPoints, 29)]
        [TestCase(ScoreType.Bloodied, 14)]
        [TestCase(ScoreType.ArmorClass, 19)]
        [TestCase(ScoreType.Fortitude, 13)]
        [TestCase(ScoreType.Reflex, 18)]
        [TestCase(ScoreType.Will, 18)]
        [TestCase(ScoreType.Speed, 6)]
        [TestCase(ScoreType.Fly, 6)]
        [TestCase(ScoreType.Climb, 0)]
        [TestCase(ScoreType.Swim, 0)]
        [TestCase(ScoreType.SavingThrows, 0)]
        [TestCase(ScoreType.Acrobatics, 6)]
        [TestCase(ScoreType.Athletics, 3)]
        [TestCase(ScoreType.Conspiracy, 0)]
        [TestCase(ScoreType.Insight, 12)]
        [TestCase(ScoreType.Interaction, 8)]
        [TestCase(ScoreType.Mechanics, 0)]
        [TestCase(ScoreType.Nature, 8)]
        [TestCase(ScoreType.Perception, 12)]
        [TestCase(ScoreType.Science, 0)]
        [TestCase(ScoreType.Stealth, 6)]
        [TestCase(ScoreType.Level, 3)]
        [TestCase(ScoreType.OpportunityAttackAttackBonus, 0)]
        [TestCase(ScoreType.OpportunityAttackArmorClassBonus, 0)]
        [TestCase(ScoreType.StrengthCheck, 3)]
        [TestCase(ScoreType.ConstitutionCheck, 1)]
        [TestCase(ScoreType.DexterityCheck, 6)]
        [TestCase(ScoreType.IntelligenceCheck, 0)]
        [TestCase(ScoreType.WisdomCheck, 8)]
        [TestCase(ScoreType.CharismaCheck, 4)]
        [TestCase(ScoreType.FireResistance, 0)]
        [TestCase(ScoreType.ElectricityResistance, 0)]
        [TestCase(ScoreType.ColdResistance, 0)]
        [TestCase(ScoreType.PhysicalResistance, 0)]
        [TestCase(ScoreType.FireVulnerability, 0)]
        public override void TestScore(ScoreType scoreType, int expectedValue)
        {
            base.TestScore(scoreType, expectedValue);
        }

        [TestCase(typeof(GammaWorldCharacter.Powers.BasicAttack), 0, 9, 1, DiceType.d12, 6, "physical damage.")]
        [TestCase(typeof(GammaWorldCharacter.Powers.Origins.TerrifyingShriek), 0, 8, 1, DiceType.d6, 8, "psychic damage and you slide the target 1 square.")]
        [TestCase(typeof(GammaWorldCharacter.Powers.Origins.UncannyStrike), 0, 11, 1, DiceType.d12, 8, "physical damage and the target grants combat advantage until the end of your next turn")]
        public override void TestAttackPower(Type type, int attack, int attackBonus, int damageDiceCount, DiceType damageDiceType, int damageBonus, string additionalText)
        {
            base.TestAttackPower(type, attack, attackBonus, damageDiceCount, damageDiceType, damageBonus, additionalText);
        }

        [TestCase(typeof(GammaWorldCharacter.Powers.SecondWind), "You heal 14 hit points and gain +2 to all defenses until the end of your next turn.")]
        [TestCase(typeof(GammaWorldCharacter.Powers.Origins.FlapAway), "You fly 2 squares without provoking opportunity attacks. If you don't land at the end of this movement, you fall.")]
        public override void TestUtilityPower(Type type, string expectedEffect)
        {
            base.TestUtilityPower(type, expectedEffect);
        }

        [TestCase(typeof(GammaWorldCharacter.Powers.BasicAttack), ActionType.Standard, AttackType.Ranged, "10", 64, null, 0, PowerFrequency.AtWill, PowerSource.None, null)]
        [TestCase(typeof(GammaWorldCharacter.Powers.SecondWind), ActionType.Minor, AttackType.Personal, null, 0, "You heal 14 hit points and gain +2 to all defenses until the end of your next turn.", 1, PowerFrequency.Encounter, PowerSource.None, null)]
        [TestCase(typeof(GammaWorldCharacter.Powers.Origins.TerrifyingShriek), ActionType.Standard, AttackType.Close, "burst 2", 256, null, 0, PowerFrequency.AtWill, PowerSource.Bio, null)]
        [TestCase(typeof(GammaWorldCharacter.Powers.Origins.UncannyStrike), ActionType.Standard, AttackType.Ranged, "weapon", 64, null, 0, PowerFrequency.AtWill, PowerSource.Psi, null)]
        [TestCase(typeof(GammaWorldCharacter.Powers.Origins.FlapAway), ActionType.ImmediateReaction, AttackType.Personal, null, 0, "You fly 2 squares without provoking opportunity attacks. If you don't land at the end of this movement, you fall.", 0, PowerFrequency.Encounter, PowerSource.Bio, "An enemy enters a square adjacent to you.")]
        public override void TestPower(Type type, ActionType actionType, AttackType attackType, string range, DamageTypes damageTypes, string effect,
            EffectTypes effectTypes, PowerFrequency frequency, PowerSource powerSource, string trigger)
        {
            base.TestPower(type, actionType, attackType, range, damageTypes, effect, effectTypes, frequency, powerSource, trigger);
        }

        /// <summary>
        /// Create the test character.
        /// </summary>
        protected override Character Character
        {
            get
            {
                if (testCharacter == null)
                {
                    testCharacter = Level03Characters.Hermes;
                }
                return testCharacter;
            }
        }
    }
}
