using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;
using GammaWorldCharacter;
using GammaWorldCharacter.Gear;
using GammaWorldCharacter.Origins;
using GammaWorldCharacter.Powers;
using GammaWorldCharacter.Traits;
using GammaWorldCharacter.Samples;
using GammaWorldCharacter.Test.Integration;

namespace GammaWorldCharacter.Test.Integration
{
    /// <summary> 
    /// Autogenerated character test
    /// </summary>
    [TestFixture]
    public class TestLevel02Virtus : CharacterTest
    {
        private Character testCharacter;

        [TestCase(ScoreType.Strength, 18)]
        [TestCase(ScoreType.Constitution, 16)]
        [TestCase(ScoreType.Dexterity, 12)]
        [TestCase(ScoreType.Intelligence, 10)]
        [TestCase(ScoreType.Wisdom, 9)]
        [TestCase(ScoreType.Charisma, 8)]
        [TestCase(ScoreType.StrengthModifier, 4)]
        [TestCase(ScoreType.ConstitutionModifier, 3)]
        [TestCase(ScoreType.DexterityModifier, 1)]
        [TestCase(ScoreType.IntelligenceModifier, 0)]
        [TestCase(ScoreType.WisdomModifier, -1)]
        [TestCase(ScoreType.CharismaModifier, -1)]
        [TestCase(ScoreType.Initiative, 3)]
        [TestCase(ScoreType.HitPoints, 33)]
        [TestCase(ScoreType.Bloodied, 16)]
        [TestCase(ScoreType.ArmorClass, 19)]
        [TestCase(ScoreType.Fortitude, 18)]
        [TestCase(ScoreType.Reflex, 15)]
        [TestCase(ScoreType.Will, 11)]
        [TestCase(ScoreType.Speed, 6)]
        [TestCase(ScoreType.Fly, 0)]
        [TestCase(ScoreType.Climb, 0)]
        [TestCase(ScoreType.Swim, 0)]
        [TestCase(ScoreType.SavingThrows, 0)]
        [TestCase(ScoreType.Acrobatics, 3)]
        [TestCase(ScoreType.Athletics, 14)]
        [TestCase(ScoreType.Conspiracy, 2)]
        [TestCase(ScoreType.Insight, 5)]
        [TestCase(ScoreType.Interaction, 1)]
        [TestCase(ScoreType.Mechanics, 2)]
        [TestCase(ScoreType.Nature, 1)]
        [TestCase(ScoreType.Perception, 1)]
        [TestCase(ScoreType.Science, 2)]
        [TestCase(ScoreType.Stealth, 3)]
        [TestCase(ScoreType.Level, 2)]
        [TestCase(ScoreType.OpportunityAttackAttackBonus, 0)]
        [TestCase(ScoreType.OpportunityAttackArmorClassBonus, 0)]
        [TestCase(ScoreType.StrengthCheck, 6)]
        [TestCase(ScoreType.ConstitutionCheck, 5)]
        [TestCase(ScoreType.DexterityCheck, 3)]
        [TestCase(ScoreType.IntelligenceCheck, 2)]
        [TestCase(ScoreType.WisdomCheck, 1)]
        [TestCase(ScoreType.CharismaCheck, 1)]
        [TestCase(ScoreType.FireResistance, 0)]
        [TestCase(ScoreType.ElectricityResistance, 0)]
        [TestCase(ScoreType.ColdResistance, 0)]
        [TestCase(ScoreType.PhysicalResistance, 0)]
        [TestCase(ScoreType.FireVulnerability, 0)]
        public override void TestScore(ScoreType scoreType, int expectedValue)
        {
            base.TestScore(scoreType, expectedValue);
        }

        [TestCase(typeof(GammaWorldCharacter.Powers.BasicAttack), 0, 8, 2, DiceType.d8, 6, "physical damage.")]
        [TestCase(typeof(GammaWorldCharacter.Powers.Origins.Brickbat), 0, 8, 2, DiceType.d8, 4, "physical damage and you knock the target prone")]
        [TestCase(typeof(GammaWorldCharacter.Powers.Origins.GravitationalPulse), 0, 5, 1, DiceType.d10, 7, "physical damage and the target is slowed until the end of your next turn.")]
        public override void TestAttackPower(Type type, int attack, int attackBonus, int damageDiceCount, DiceType damageDiceType, int damageBonus, string additionalText)
        {
            base.TestAttackPower(type, attack, attackBonus, damageDiceCount, damageDiceType, damageBonus, additionalText);
        }

        [TestCase(typeof(GammaWorldCharacter.Powers.SecondWind), "You heal 16 hit points and gain +2 to all defenses until the end of your next turn.")]
        public override void TestUtilityPower(Type type, string expectedEffect)
        {
            base.TestUtilityPower(type, expectedEffect);
        }

        [TestCase(typeof(GammaWorldCharacter.Powers.BasicAttack), ActionType.Standard, AttackType.Melee, "1", 64, null, 0, PowerFrequency.AtWill, PowerSource.None, null)]
        [TestCase(typeof(GammaWorldCharacter.Powers.SecondWind), ActionType.Minor, AttackType.Personal, null, 0, "You heal 16 hit points and gain +2 to all defenses until the end of your next turn.", 1, PowerFrequency.Encounter, PowerSource.None, null)]
        [TestCase(typeof(GammaWorldCharacter.Powers.Origins.Brickbat), ActionType.Standard, AttackType.Close, "burst 1", 64, null, 0, PowerFrequency.AtWill, PowerSource.Bio, null)]
        [TestCase(typeof(GammaWorldCharacter.Powers.Origins.GravitationalPulse), ActionType.Standard, AttackType.Ranged, "10", 64, null, 0, PowerFrequency.AtWill, PowerSource.Dark, null)]
        public override void TestPower(Type type, ActionType actionType, AttackType attackType, string range, DamageTypes damageTypes, string effect,
            EffectTypes effectTypes, PowerFrequency frequency, PowerSource powerSource, string trigger)
        {
            base.TestPower(type, actionType, attackType, range, damageTypes, effect, effectTypes, frequency, powerSource, trigger);
        }

        /// <summary>
        /// Create the test character.
        /// </summary>
        protected override Character Character
        {
            get
            {
                if (testCharacter == null)
                {
                    testCharacter = Level02Characters.Virtus;
                }
                return testCharacter;
            }
        }
    }
}
