using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;
using GammaWorldCharacter;
using GammaWorldCharacter.Gear;
using GammaWorldCharacter.Origins;
using GammaWorldCharacter.Powers;
using GammaWorldCharacter.Traits;
using GammaWorldCharacter.Samples;
using GammaWorldCharacter.Test.Integration;

namespace GammaWorldCharacter.Test.Integration
{
    /// <summary> 
    /// Autogenerated character test
    /// </summary>
    [TestFixture]
    public class TestLevel01Clip: CharacterTest
    {
        private Character testCharacter;

        [TestCase(ScoreType.Strength, 12)]
        [TestCase(ScoreType.Constitution, 18)]
        [TestCase(ScoreType.Dexterity, 11)]
        [TestCase(ScoreType.Intelligence, 16)]
        [TestCase(ScoreType.Wisdom, 10)]
        [TestCase(ScoreType.Charisma, 15)]
        [TestCase(ScoreType.StrengthModifier, 1)]
        [TestCase(ScoreType.ConstitutionModifier, 4)]
        [TestCase(ScoreType.DexterityModifier, 0)]
        [TestCase(ScoreType.IntelligenceModifier, 3)]
        [TestCase(ScoreType.WisdomModifier, 0)]
        [TestCase(ScoreType.CharismaModifier, 2)]
        [TestCase(ScoreType.Initiative, 1)]
        [TestCase(ScoreType.HitPoints, 30)]
        [TestCase(ScoreType.Bloodied, 15)]
        [TestCase(ScoreType.ArmorClass, 18)]
        [TestCase(ScoreType.Fortitude, 17)]
        [TestCase(ScoreType.Reflex, 16)]
        [TestCase(ScoreType.Will, 13)]
        [TestCase(ScoreType.Speed, 6)]
        [TestCase(ScoreType.Fly, 0)]
        [TestCase(ScoreType.Climb, 6)]
        [TestCase(ScoreType.Swim, 0)]
        [TestCase(ScoreType.SavingThrows, 0)]
        [TestCase(ScoreType.Acrobatics, 1)]
        [TestCase(ScoreType.Athletics, 2)]
        [TestCase(ScoreType.Conspiracy, 4)]
        [TestCase(ScoreType.Insight, 1)]
        [TestCase(ScoreType.Interaction, 3)]
        [TestCase(ScoreType.Mechanics, 8)]
        [TestCase(ScoreType.Nature, 1)]
        [TestCase(ScoreType.Perception, 1)]
        [TestCase(ScoreType.Science, 12)]
        [TestCase(ScoreType.Stealth, 1)]
        [TestCase(ScoreType.Level, 1)]
        [TestCase(ScoreType.OpportunityAttackAttackBonus, 0)]
        [TestCase(ScoreType.OpportunityAttackArmorClassBonus, 0)]
        [TestCase(ScoreType.StrengthCheck, 2)]
        [TestCase(ScoreType.ConstitutionCheck, 5)]
        [TestCase(ScoreType.DexterityCheck, 1)]
        [TestCase(ScoreType.IntelligenceCheck, 4)]
        [TestCase(ScoreType.WisdomCheck, 1)]
        [TestCase(ScoreType.CharismaCheck, 3)]
        [TestCase(ScoreType.FireResistance, 0)]
        [TestCase(ScoreType.ElectricityResistance, 0)]
        [TestCase(ScoreType.ColdResistance, 0)]
        [TestCase(ScoreType.PhysicalResistance, 0)]
        [TestCase(ScoreType.FireVulnerability, 0)]
        public override void TestScore(ScoreType scoreType, int expectedValue)
        {
            base.TestScore(scoreType, expectedValue);
        }

        [TestCase(typeof(GammaWorldCharacter.Powers.BasicAttack), 0, 7, 1, DiceType.d10, 5, "physical damage.")]
        [TestCase(typeof(GammaWorldCharacter.Powers.Origins.EauDeRoach), 0, 5, 2, DiceType.d8, 6, "acid damage and you push the target 1 square.")]
        [TestCase(typeof(GammaWorldCharacter.Powers.Origins.MachineGrip), 0, 4, 1, DiceType.d10, 5, "physical damage and the target is immobilized until the start of your next turn. If you move to a square that isn't adjacent to the target, the immobilization ends.")]
        public override void TestAttackPower(Type type, int attack, int attackBonus, int damageDiceCount, DiceType damageDiceType, int damageBonus, string additionalText)
        {
            base.TestAttackPower(type, attack, attackBonus, damageDiceCount, damageDiceType, damageBonus, additionalText);
        }

        [TestCase(typeof(GammaWorldCharacter.Powers.SecondWind), "You heal 15 hit points and gain +2 to all defenses until the end of your next turn.")]
        public override void TestUtilityPower(Type type, string expectedEffect)
        {
            base.TestUtilityPower(type, expectedEffect);
        }

        [TestCase(typeof(GammaWorldCharacter.Powers.BasicAttack), ActionType.Standard, AttackType.Melee, "1", 64, null, 0, PowerFrequency.AtWill, PowerSource.None, null)]
        [TestCase(typeof(GammaWorldCharacter.Powers.SecondWind), ActionType.Minor, AttackType.Personal, null, 0, "You heal 15 hit points and gain +2 to all defenses until the end of your next turn.", 1, PowerFrequency.Encounter, PowerSource.None, null)]
        [TestCase(typeof(GammaWorldCharacter.Powers.Origins.EauDeRoach), ActionType.Standard, AttackType.Melee, "1", 1, null, 0, PowerFrequency.AtWill, PowerSource.Bio, null)]
        [TestCase(typeof(GammaWorldCharacter.Powers.Origins.MachineGrip), ActionType.Standard, AttackType.Melee, "1", 64, null, 0, PowerFrequency.AtWill, PowerSource.Dark, null)]
        public override void TestPower(Type type, ActionType actionType, AttackType attackType, string range, DamageTypes damageTypes, string effect, 
            EffectTypes effectTypes, PowerFrequency frequency, PowerSource powerSource, string trigger)
        {
            base.TestPower(type, actionType, attackType, range, damageTypes, effect, effectTypes, frequency, powerSource, trigger);
        }

        /// <summary>
        /// Create the test character.
        /// </summary>
        protected override Character Character
        {
            get
            {
                if (testCharacter == null)
                {
                    testCharacter = Level01Characters.Clip;
                }
                return testCharacter;
            }
        }
    }
}
